title: "Farjana Yesmin"
description: "Data Scientist & ML Researcher"
baseurl: ""
url: "https://farjana-yesmin.github.io"
theme: minima

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed

exclude:
  - README.md
